---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true
        ## Create Route on the Openshift, and bind with service.

  rules:
    - name: "Trigger Metro DR Flow"
      condition: true
      action:
        run_job_template:
          name: "Metro DR Failover Workflow"
          organization: "Default"

    # - name: "Say Hello"
    #   condition: true
    #   action:
    #     run_job_template:
    #       name: "Hello World"
    #       organization: "Default"

    # - name: SELinux was enabled
    #   condition: event.alert.labels.alertname == "selinux disabled" and event.alert.status == "resolved"
    #   action:
    #     debug:
    #       msg: "enabled on: {{ event.meta.hosts }}"

    # - name: Capture all other events from this source
    #   condition: event.alert is defined
    #   action:
    #     debug:


    # - name: New admin user
    #   condition: >
    #     event.body.fields.role is search("SYSTEM_ROLE_ADMIN")
    #     and event.body.tags.username != "admin"
    #     and event.body.tags.username != "student"
    #   action:
    #     post_event:
    #       event:
    #         new_user: "{{ event.body.tags.username }}"
    #         managed_node: "{{ event.body.tags.source }}"


    # - name: Send a chat message
    #   condition: event.new_user is defined
    #   action:
    #     run_job_template:
    #       name: Send a message to mattermost
    #       organization: Default
    #       post_events: true
    #       job_args:
    #         extra_vars:
    #           admin: "{{ event.new_user }}"
    #           node: "{{ event.managed_node }}"
